name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: bazel-disk-cache
      uses: actions/cache@v2.0.0
      env:
        cache-name: citest-bazel-disk-cache-ubuntu
      with:
        path: ~/bazel_disk_cache
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.github/workflows/CACHE_VERSION') }}
    - name: build
      run: bazel build --disk_cache=~/bazel_disk_cache --cxxopt -std=c++17 //...:all
    - name: test
      run: bazel test --disk_cache=~/bazel_disk_cache --cxxopt -std=c++17 //...:all

  build-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: bazel-disk-cache
      uses: actions/cache@v2.0.0
      env:
        cache-name: citest-bazel-disk-cache-windows
      with:
        path: ~\AppData\Roaming\bazel_disk_cache
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.github/workflows/CACHE_VERSION') }}
    - name: build
      run: bazel build --disk_cache="$env:USERPROFILE\AppData\Roaming\bazel_disk_cache" --cxxopt /std:c++17 //...:all
    - name: test
      run: bazel test --disk_cache="$env:USERPROFILE\AppData\Roaming\bazel_disk_cache" --cxxopt /std:c++17 //...:all

  build-macos:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: bazel-disk-cache
      uses: actions/cache@v2.0.0
      env:
        cache-name: citest-bazel-disk-cache-macos
      with:
        path: ~/bazel_disk_cache
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.github/workflows/CACHE_VERSION') }}
    - name: build
      run: bazel build --disk_cache=~/bazel_disk_cache --cxxopt -std=c++17 //...:all
    - name: test
      run: bazel test --disk_cache=~/bazel_disk_cache --cxxopt -std=c++17 //...:all
